"""Create the file model}

Revision ID: 009fce8cb80f
Revises: d4867f3a4c0a
Create Date: 2023-12-16 00:29:27.580334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "009fce8cb80f"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("s3_location", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("indexed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_id"), "file", ["id"], unique=False)
    op.create_index(op.f("ix_file_name"), "file", ["name"], unique=False)
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_file_name"), table_name="file")
    op.drop_index(op.f("ix_file_id"), table_name="file")
    op.drop_table("file")
    # ### end Alembic commands ###
